### ISSUE TITLE
Update namespace from `Tailwind.Css` to `TailwindCss`

### ISSUE THREAD

**Issue by xt0rted** [xt0rted/tailwindcss-tag-helpers#159]
I can't really see a reason to keep the namespace as `Tailwind.Css` vs. the easier `TailwindCss` so before v1 this should probably be updated.

**Comment by westerandr** [comment]
Can I be assigned this issue please?

**Comment by xt0rted** [comment]
Hi @westerandr, thanks for the interest in this. After thinking about it more I realized the current namespace matches [one of my other projects](https://github.com/xt0rted/heroicons-tag-helper) so I'm not going to make this change for now.
